FROM ubuntu
MAINTAINER Dikshant
RUN apt-get update
RUN apt-get install -y nginx
RUN rm -rf [/var/www/html/index.nginx-debain.html]
COPY index.html /var/www/html/
EXPOSE 80
CMD nginx -g 'daemon off;' 

